apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: todo-app
type: Opaque
data:
  # Base64 encoded values for in-cluster PostgreSQL
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==  # postgres-service
  DB_NAME: dG9kb2Ri  # tododb
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cGFzc3dvcmQ=  # password
