apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
  namespace: todo-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      completed BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ
    );

    -- Ensure updated_at column exists (for pre-existing tables)
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'todos' AND column_name = 'updated_at'
      ) THEN
        ALTER TABLE todos ADD COLUMN updated_at TIMESTAMPTZ;
      END IF;
    END $$;

    -- Trigger to auto-update updated_at on UPDATE
    CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at := NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'todos_set_updated_at'
      ) THEN
        CREATE TRIGGER todos_set_updated_at
        BEFORE UPDATE ON todos
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
      END IF;
    END $$;

    -- optional seed
    INSERT INTO todos (title, description, completed)
    VALUES ('First task', 'Created by db-init job', false)
    ON CONFLICT DO NOTHING;
